name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
         python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python-version }}
      - run: sudo apt-get install ffmpeg
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101,B403,B605,B607 .
      - run: black --check . || true
      - run: codespell --ignore-words-list="fo"
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements/requirements.txt
      - run: mkdir -p .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive .
      - run: pytest .
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
